// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK-UxvxY3Lggdf77uXu1fsb_5Xa3Rjsws',
    appId: '1:926102685964:web:1cef98b1e76687eeefa129',
    messagingSenderId: '926102685964',
    projectId: 'sportify-f302a',
    authDomain: 'sportify-f302a.firebaseapp.com',
    storageBucket: 'sportify-f302a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8Ibs9TUw0pDOsUUlnvFbPJacEp6uWpLk',
    appId: '1:926102685964:android:4ddd697da00de6abefa129',
    messagingSenderId: '926102685964',
    projectId: 'sportify-f302a',
    storageBucket: 'sportify-f302a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqt9oHqpAPch223ewj1hVPn_jhsiyRbMQ',
    appId: '1:926102685964:ios:82d9815acead680eefa129',
    messagingSenderId: '926102685964',
    projectId: 'sportify-f302a',
    storageBucket: 'sportify-f302a.appspot.com',
    iosBundleId: 'com.example.sportify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqt9oHqpAPch223ewj1hVPn_jhsiyRbMQ',
    appId: '1:926102685964:ios:82d9815acead680eefa129',
    messagingSenderId: '926102685964',
    projectId: 'sportify-f302a',
    storageBucket: 'sportify-f302a.appspot.com',
    iosBundleId: 'com.example.sportify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDK-UxvxY3Lggdf77uXu1fsb_5Xa3Rjsws',
    appId: '1:926102685964:web:8042219d4b7706d1efa129',
    messagingSenderId: '926102685964',
    projectId: 'sportify-f302a',
    authDomain: 'sportify-f302a.firebaseapp.com',
    storageBucket: 'sportify-f302a.appspot.com',
  );
}
